import React, { useState, useEffect } from 'react';
import { 
  ShieldCheck, 
  ShieldAlert, 
  Eye, 
  EyeOff, 
  CheckCircle2, 
  XCircle, 
  Search, 
  Layers, 
  Info, 
  Send, 
  User, 
  Check, 
  AlertTriangle, 
  Clock, 
  Maximize2,
  Video,
  Camera,
  Filter,
  Sliders,
  Sparkles,
  GitCompare,
  Cpu,
  BadgeAlert
} from 'lucide-react';

export default function EvidenceReview({ 
  alerts = [], 
  snapshots = [], 
  centres = [], 
  onVerifyAlert,
  onVerifySnapshot,
  initialSnapshotId,
  userRole,
  onRefreshData,
  onNavigateToTab
}) {
  const [selectedSnapshotId, setSelectedSnapshotId] = useState(
    initialSnapshotId || snapshots[0]?.snapshot_id || ''
  );
  const [filterMode, setFilterMode] = useState('all'); // 'all', 'flagged', 'verified', 'pending'
  const [showPersonBoxes, setShowPersonBoxes] = useState(true);
  const [showDiscrepancyHighlight, setShowDiscrepancyHighlight] = useState(true);
  const [showOSD, setShowOSD] = useState(true);

  // Verification Form State
  const [officerName, setOfficerName] = useState(
    userRole === 'Monitoring Officer' ? 'Dr. Alok Sharma (Deputy Director)' : 'Monitoring Officer On Duty'
  );
  const [decisionType, setDecisionType] = useState('CONFIRM_FLAG'); // 'CONFIRM_FLAG', 'DISMISS_FALSE_POSITIVE', 'OVERRIDE_COUNT'
  const [manualCount, setManualCount] = useState(20);
  const [remarks, setRemarks] = useState('');
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [verificationFeedback, setVerificationFeedback] = useState(null);

  // Keep selected snapshot in sync
  useEffect(() => {
    if (initialSnapshotId) {
      setSelectedSnapshotId(initialSnapshotId);
    } else if (snapshots.length > 0 && !selectedSnapshotId) {
      setSelectedSnapshotId(snapshots[0].snapshot_id);
    }
  }, [initialSnapshotId, snapshots]);

  // Find active snapshot
  const activeSnapshot = snapshots.find(s => s.snapshot_id === selectedSnapshotId) || snapshots[0];
  const activeCentre = centres.find(c => c.centre_id === activeSnapshot?.centre_id);
  const linkedAlert = alerts.find(a => a.evidence_id === activeSnapshot?.snapshot_id);

  // Sync manual count to active snapshot count
  useEffect(() => {
    if (activeSnapshot) {
      setManualCount(activeSnapshot.people_count);
    }
  }, [activeSnapshot?.snapshot_id]);

  // Filter snapshots
  const filteredSnapshots = snapshots.filter(s => {
    const isFlagged = Boolean(
      s.is_flagged || 
      s.flag_type || 
      (s.temporal_diff && s.temporal_diff.people_count_delta < 0) || 
      (s.discrepancy && s.discrepancy < 0) || 
      s.verification_status?.includes('Confirmed')
    );
    const isVerified = !!s.verification;

    if (filterMode === 'flagged') return isFlagged;
    if (filterMode === 'verified') return isVerified;
    if (filterMode === 'pending') return !isVerified;
    return true;
  });

  // Calculate flags generated by YOLO for active snapshot
  const calculateYoloFlags = (snap) => {
    if (!snap) return [];
    const flags = [];

    // 0. Explicit Incident Flag (Accident, Missing Student, Irregularity)
    if (snap.is_flagged || snap.flag_type) {
      flags.push({
        id: `flag-incident-${snap.flag_id || snap.snapshot_id || Date.now()}`,
        category: snap.category || (snap.flag_type === 'ACCIDENT' ? 'Emergency / Physical Hazard' : (snap.flag_type === 'MISSING_STUDENT' ? 'Attendance Mismatch' : 'Compliance Non-Compliance')),
        severity: snap.flag_severity || (snap.flag_type === 'ACCIDENT' ? 'Critical' : 'High'),
        title: snap.flag_title || `${snap.flag_type || 'Incident'} at ${snap.video_timestamp || '00:00'}`,
        description: snap.flag_description || snap.notes || `Incident flagged at video time ${snap.video_timestamp || '00:00'}. Timestamped CCTV evidence captured.`,
        action_required: snap.flag_type === 'ACCIDENT' 
          ? '🚨 Urgent: Dispatch emergency response & review CCTV footage immediately' 
          : '⚠️ Reconcile roll call register with video headcount and verify student presence'
      });
    }

    const delta = snap.temporal_diff ? snap.temporal_diff.people_count_delta : (snap.discrepancy || 0);

    // 1. Headcount Variance Flag
    if (delta < 0) {
      flags.push({
        id: 'flag-headcount-deficit',
        category: 'Attendance Anomaly',
        severity: Math.abs(delta) >= 5 ? 'Critical' : 'High',
        title: `Headcount Deficit (${Math.abs(delta)} Trainees Missing)`,
        description: `YOLO detector observed ${snap.people_count} trainees in this frame versus ${snap.temporal_diff ? snap.temporal_diff.people_count_previous : (snap.people_count - delta)} in baseline frame. Net shortfall of ${Math.abs(delta)} attendees.`,
        action_required: 'Confirm if trainees exited or moved out of camera FOV.'
      });
    }

    // 2. Capacity Discrepancy Flag
    if (snap.reported_count && snap.people_count < snap.reported_count) {
      const shortage = snap.reported_count - snap.people_count;
      flags.push({
        id: 'flag-capacity-mismatch',
        category: 'Accreditation Compliance',
        severity: shortage >= 8 ? 'Critical' : 'Medium',
        title: `Capacity Under-Utilization (${shortage} Desks Unoccupied)`,
        description: `Centre has ${snap.reported_count} approved capacity, but only ${snap.people_count} trainees are visually seated.`,
        action_required: 'Verify if batch induction is in progress or unauthorized absenteeism.'
      });
    }


    // 4. Bandwidth Optimization
    flags.push({
      id: 'flag-bandwidth-opt',
      category: 'Edge Node Efficiency',
      severity: 'Compliant Info',
      title: 'Edge Compression Active (99.5% Bandwidth Saved)',
      description: `Compressed telemetry transmission (42.1 KB payload instead of 8.5 MB continuous stream).`,
      action_required: 'Bandwidth quota preserved.'
    });

    return flags;
  };

  const activeFlags = calculateYoloFlags(activeSnapshot);

  // Submit Verification Decision
  const handleVerify = async () => {
    if (!activeSnapshot) return;
    setIsSubmitting(true);
    try {
      if (onVerifySnapshot) {
        await onVerifySnapshot(activeSnapshot.snapshot_id, {
          officer_name: officerName,
          decision: decisionType,
          remarks: remarks || `Officer ${officerName} verified snapshot flags: ${decisionType}`,
          override_count: decisionType === 'OVERRIDE_COUNT' ? Number(manualCount) : activeSnapshot.people_count
        });
      }

      // Also verify linked alert if present
      if (linkedAlert && onVerifyAlert) {
        const alertDecision = decisionType === 'DISMISS_FALSE_POSITIVE' ? 'REJECT' : 'ACCEPT';
        await onVerifyAlert(linkedAlert.alert_id, {
          officer_name: officerName,
          decision: alertDecision,
          remarks: remarks || `Officer ${officerName} reviewed snapshot evidence and recorded decision: ${alertDecision}`
        });
      }

      setVerificationFeedback({
        decision: decisionType,
        time: new Date().toLocaleTimeString(),
        message: decisionType === 'DISMISS_FALSE_POSITIVE' 
          ? 'Flag dismissed as false positive. Record marked compliant.' 
          : decisionType === 'OVERRIDE_COUNT'
          ? `Headcount manually overridden to ${manualCount} trainees.`
          : 'YOLO discrepancy flag confirmed. Logged to central audit ledger.'
      });

      setRemarks('');
      if (onRefreshData) onRefreshData();
      setTimeout(() => setVerificationFeedback(null), 5000);
    } catch (err) {
      console.error(err);
    } finally {
      setIsSubmitting(false);
    }
  };

  // If no snapshots exist in database
  if (snapshots.length === 0) {
    return (
      <div>
        <div className="section-header">
          <div className="section-title">
            <ShieldCheck size={18} style={{ color: '#38bdf8' }} />
            <span>Snapshots & YOLO Flag Verification Studio</span>
          </div>
        </div>

        <div className="table-card" style={{ padding: '3.5rem 1.5rem', textAlign: 'center', color: 'var(--text-muted)' }}>
          <ShieldAlert size={44} style={{ color: '#475569', marginBottom: '0.85rem' }} />
          <h3 style={{ fontSize: '1rem', fontWeight: 600, color: 'var(--text-primary)' }}>
            No Snapshot Frames Available for Review
          </h3>
          <p style={{ fontSize: '0.75rem', marginTop: '0.4rem', maxWidth: '520px', margin: '0.4rem auto 1.2rem' }}>
            To verify YOLO detection overlays and inspect flags generated by the computer vision model, 
            upload a CCTV recording in the <strong>CCTV Video & Snapshot Diff</strong> studio and extract snapshots.
          </p>
          {onNavigateToTab && (
            <button className="btn-primary" onClick={() => onNavigateToTab('video-studio')}>
              <Video size={13} />
              <span>Go to CCTV Video Studio</span>
            </button>
          )}
        </div>
      </div>
    );
  }

  const isSnapFlagged = (activeSnapshot?.temporal_diff && activeSnapshot.temporal_diff.people_count_delta < 0) || 
                        (activeSnapshot?.discrepancy && activeSnapshot.discrepancy < 0) ||
                        activeSnapshot?.verification_status?.includes('Confirmed');

  return (
    <div>
      {/* Top Header Bar */}
      <div className="section-header">
        <div className="section-title">
          <ShieldCheck size={18} style={{ color: '#38bdf8' }} />
          <span>Snapshots & YOLO Flag Verification Studio</span>
          <span className="badge badge-info" style={{ fontFamily: 'var(--font-mono)' }}>
            {snapshots.length} Total Frames
          </span>
          <span className="badge badge-info" style={{ fontFamily: 'var(--font-mono)' }}>
            ⚡ YOLOv11 Optical Feed (Raw)
          </span>
          {alerts.length > 0 && (
            <span className="badge badge-critical">
              {alerts.length} Active System Alerts
            </span>
          )}
        </div>

        {/* Filter controls */}
        <div className="section-actions">
          <div style={{ display: 'flex', background: 'var(--bg-input)', padding: '2px', borderRadius: '4px', border: '1px solid var(--border-subtle)' }}>
            <button 
              className={`nav-tab-btn ${filterMode === 'all' ? 'active' : ''}`}
              style={{ padding: '2px 8px', fontSize: '0.7rem' }}
              onClick={() => setFilterMode('all')}
            >
              All ({snapshots.length})
            </button>
            <button 
              className={`nav-tab-btn ${filterMode === 'flagged' ? 'active' : ''}`}
              style={{ padding: '2px 8px', fontSize: '0.7rem', color: '#f87171' }}
              onClick={() => setFilterMode('flagged')}
            >
              Flagged by YOLO
            </button>
            <button 
              className={`nav-tab-btn ${filterMode === 'pending' ? 'active' : ''}`}
              style={{ padding: '2px 8px', fontSize: '0.7rem', color: '#fbbf24' }}
              onClick={() => setFilterMode('pending')}
            >
              Pending Review
            </button>
            <button 
              className={`nav-tab-btn ${filterMode === 'verified' ? 'active' : ''}`}
              style={{ padding: '2px 8px', fontSize: '0.7rem', color: '#34d399' }}
              onClick={() => setFilterMode('verified')}
            >
              Verified
            </button>
          </div>
        </div>
      </div>

      {/* Verification Feedback Banner */}
      {verificationFeedback && (
        <div style={{
          padding: '0.5rem 0.75rem',
          marginBottom: '0.65rem',
          borderRadius: '4px',
          fontSize: '0.74rem',
          background: 'rgba(16, 185, 129, 0.15)',
          border: '1px solid #10b981',
          color: '#6ee7b7',
          display: 'flex',
          alignItems: 'center',
          gap: '0.5rem'
        }}>
          <CheckCircle2 size={16} />
          <strong>Verification Logged [{verificationFeedback.time}]:</strong>
          <span>{verificationFeedback.message}</span>
        </div>
      )}

      {/* Snapshot Filmstrip Gallery */}
      <div className="table-card" style={{ marginBottom: '0.75rem', padding: '0.45rem 0.65rem' }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '0.35rem' }}>
          <strong style={{ fontSize: '0.72rem', color: 'var(--text-muted)' }}>
            Select Snapshot to Inspect YOLO Flags ({filteredSnapshots.length} matching filter):
          </strong>
          <span style={{ fontSize: '0.66rem', color: 'var(--text-dim)' }}>
            Click any frame to view detection boxes & verify flags
          </span>
        </div>

        <div style={{ display: 'flex', gap: '0.5rem', overflowX: 'auto', paddingBottom: '0.25rem' }}>
          {filteredSnapshots.map(snap => {
            const isSelected = snap.snapshot_id === selectedSnapshotId;
            const hasDelta = snap.temporal_diff && snap.temporal_diff.people_count_delta < 0;
            const isVer = !!snap.verification;

            return (
              <div
                key={snap.snapshot_id}
                onClick={() => setSelectedSnapshotId(snap.snapshot_id)}
                style={{
                  minWidth: '150px',
                  maxWidth: '170px',
                  background: isSelected ? 'rgba(37, 99, 235, 0.25)' : 'var(--bg-secondary)',
                  border: `1.5px solid ${isSelected ? '#38bdf8' : hasDelta ? 'rgba(239, 68, 68, 0.5)' : 'var(--border-subtle)'}`,
                  borderRadius: '4px',
                  padding: '0.35rem',
                  cursor: 'pointer',
                  flexShrink: 0,
                  transition: 'border-color 0.15s ease'
                }}
              >
                <div style={{ position: 'relative', height: '65px', background: '#000', borderRadius: '3px', overflow: 'hidden', marginBottom: '0.3rem' }}>
                  {snap.image_data || snap.evidence_uri ? (
                    <img 
                      src={snap.image_data || snap.evidence_uri} 
                      alt="Thumbnail" 
                      style={{ width: '100%', height: '100%', objectFit: 'cover' }} 
                    />
                  ) : (
                    <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', height: '100%', fontSize: '0.65rem', color: '#64748b' }}>
                      CCTV Frame
                    </div>
                  )}

                  <div style={{ position: 'absolute', bottom: '2px', left: '2px', background: 'rgba(0,0,0,0.7)', padding: '1px 4px', borderRadius: '2px', fontSize: '0.62rem', fontFamily: 'var(--font-mono)', color: '#38bdf8' }}>
                    {snap.video_timestamp || '00:00'}
                  </div>

                  {hasDelta && (
                    <div style={{ position: 'absolute', top: '2px', right: '2px', background: '#dc2626', color: '#fff', padding: '1px 4px', borderRadius: '2px', fontSize: '0.58rem', fontWeight: 700 }}>
                      FLAGGED
                    </div>
                  )}
                </div>

                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', fontSize: '0.68rem' }}>
                  <span style={{ fontWeight: 600, color: '#f8fafc' }}>
                    {snap.people_count} Students
                  </span>
                  {isVer ? (
                    <span style={{ color: '#34d399', fontSize: '0.62rem', fontWeight: 600 }}>✓ Verified</span>
                  ) : hasDelta ? (
                    <span style={{ color: '#f87171', fontSize: '0.62rem', fontWeight: 600 }}>{snap.temporal_diff.people_count_delta} Drop</span>
                  ) : (
                    <span style={{ color: '#94a3b8', fontSize: '0.62rem' }}>Normal</span>
                  )}
                </div>
                <div style={{ fontSize: '0.58rem', color: '#38bdf8', marginTop: '0.15rem' }}>
                  ⚡ YOLO Detection Feed
                </div>
              </div>
            );
          })}
        </div>
      </div>

      {/* Main Two-Column Studio Layout */}
      <div style={{ display: 'grid', gridTemplateColumns: '1.25fr 1fr', gap: '0.65rem' }}>
        {/* Left Column: Interactive CCTV Snapshot Viewport */}
        <div className="table-card" style={{ display: 'flex', flexDirection: 'column' }}>
          <div style={{ padding: '0.45rem 0.65rem', background: 'var(--bg-table-header)', display: 'flex', justifyContent: 'space-between', alignItems: 'center', borderBottom: '1px solid var(--border-subtle)' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '0.4rem' }}>
              <Camera size={14} style={{ color: '#38bdf8' }} />
              <strong style={{ fontSize: '0.75rem' }}>
                Frame: {activeSnapshot?.snapshot_id} ({activeSnapshot?.video_timestamp || 'Time N/A'})
              </strong>
              {isSnapFlagged && (
                <span className="badge badge-critical" style={{ fontSize: '0.62rem', padding: '1px 5px' }}>
                  YOLO Anomaly Flagged
                </span>
              )}
            </div>

            {/* Layer Toggles */}
            <div style={{ display: 'flex', gap: '0.35rem' }}>
              <button 
                className="btn-secondary"
                style={{ padding: '2px 6px', fontSize: '0.66rem', background: showPersonBoxes ? 'rgba(56, 189, 248, 0.2)' : 'transparent' }}
                onClick={() => setShowPersonBoxes(!showPersonBoxes)}
              >
                Boxes ({activeSnapshot?.people_count || 0})
              </button>

              <button 
                className="btn-secondary"
                style={{ padding: '2px 6px', fontSize: '0.66rem', background: showDiscrepancyHighlight ? 'rgba(239, 68, 68, 0.2)' : 'transparent', color: '#f87171' }}
                onClick={() => setShowDiscrepancyHighlight(!showDiscrepancyHighlight)}
              >
                Ghost Delta
              </button>

              <span 
                className="badge badge-compliant"
                style={{ padding: '2px 6px', fontSize: '0.66rem', fontFamily: 'var(--font-mono)' }}
              >
                AI Detections Active
              </span>
            </div>
          </div>

          {/* Viewport Frame */}
          <div className="cctv-screen-wrapper" style={{ height: '360px', position: 'relative' }}>
            {activeSnapshot?.image_data || activeSnapshot?.evidence_uri ? (
              <img 
                src={activeSnapshot.image_data || activeSnapshot.evidence_uri} 
                alt="CCTV Evidence Snapshot" 
                className="cctv-image"
              />
            ) : (
              <div style={{ height: '100%', background: '#070b14', display: 'flex', alignItems: 'center', justifyContent: 'center', color: 'var(--text-dim)', fontSize: '0.75rem' }}>
                Extracted CCTV Video Frame
              </div>
            )}

            {/* Interactive SVG Layer for YOLO Detections & Ghost Deficits */}
            <svg className="annotation-svg-layer" viewBox="0 0 960 540" preserveAspectRatio="none">
              {/* YOLO Trainee Bounding Boxes */}
              {showPersonBoxes && (activeSnapshot?.bounding_boxes || []).map((b, i) => (
                <g key={`bbox-${i}`}>
                  <rect 
                    x={b.x} 
                    y={b.y} 
                    width={b.w} 
                    height={b.h} 
                    stroke="#10b981" 
                    strokeWidth="2" 
                    fill="rgba(16, 185, 129, 0.15)" 
                  />
                  <rect 
                    x={b.x} 
                    y={Math.max(0, b.y - 18)} 
                    width="110" 
                    height="18" 
                    fill="#059669" 
                    rx="2" 
                  />
                  <text 
                    x={b.x + 4} 
                    y={Math.max(12, b.y - 5)} 
                    fill="#ffffff" 
                    fontSize="10" 
                    fontFamily="monospace" 
                    fontWeight="bold"
                  >
                    TRAINEE #{i + 1} ({Math.round((b.conf || 0.94) * 100)}%)
                  </text>
                </g>
              ))}

              {/* Red Ghost Discrepancy Box when YOLO detects a deficit */}
              {showDiscrepancyHighlight && isSnapFlagged && (
                <g>
                  <rect 
                    x="520" 
                    y="240" 
                    width="190" 
                    height="160" 
                    stroke="#ef4444" 
                    strokeWidth="3" 
                    fill="rgba(239, 68, 68, 0.25)" 
                    strokeDasharray="6 3" 
                  />
                  <line x1="520" y1="240" x2="710" y2="400" stroke="#ef4444" strokeWidth="1.5" strokeDasharray="3 3" />
                  <line x1="520" y1="400" x2="710" y2="240" stroke="#ef4444" strokeWidth="1.5" strokeDasharray="3 3" />
                  <rect x="520" y="215" width="240" height="23" fill="#dc2626" rx="2" />
                  <text x="526" y="231" fill="#ffffff" fontSize="10.5" fontFamily="monospace" fontWeight="bold">
                    YOLO FLAG: TRAINEES MISSING
                  </text>
                </g>
              )}
            </svg>

            {/* OSD Stamp Overlay */}
            {showOSD && (
              <div className="cctv-osd-overlay" style={{ padding: '0.45rem' }}>
                <div style={{ background: 'rgba(0,0,0,0.75)', padding: '3px 8px', borderRadius: '3px', color: '#38bdf8', fontSize: '0.68rem', fontFamily: 'var(--font-mono)' }}>
                  FEED: {activeSnapshot?.source_video_name || activeSnapshot?.source_camera || 'CCTV'} • TS: {activeSnapshot?.video_timestamp || '00:00'} • COUNT: {activeSnapshot?.people_count}
                </div>
              </div>
            )}
          </div>

          {/* Snapshot Metadata Strip */}
          <div style={{ padding: '0.5rem 0.65rem', background: 'var(--bg-secondary)', borderTop: '1px solid var(--border-subtle)', display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: '0.4rem', fontSize: '0.68rem' }}>
            <div>
              <span style={{ color: 'var(--text-dim)' }}>Centre Assigned:</span>
              <div style={{ fontWeight: 600, color: '#f8fafc' }}>{activeCentre?.name || activeSnapshot?.centre_id || 'Primary Centre'}</div>
            </div>
            <div>
              <span style={{ color: 'var(--text-dim)' }}>Detected Trainees:</span>
              <div style={{ fontWeight: 700, color: '#34d399', fontFamily: 'var(--font-mono)' }}>{activeSnapshot?.people_count} persons</div>
            </div>
            <div>
              <span style={{ color: 'var(--text-dim)' }}>Confidence Score:</span>
              <div style={{ fontWeight: 600, color: '#38bdf8', fontFamily: 'var(--font-mono)' }}>{Math.round((activeSnapshot?.confidence || 0.94) * 100)}% (FP16)</div>
            </div>
            <div>
              <span style={{ color: 'var(--text-dim)' }}>Verification State:</span>
              <div style={{ fontWeight: 600, color: activeSnapshot?.verification ? '#34d399' : isSnapFlagged ? '#f87171' : '#fbbf24' }}>
                {activeSnapshot?.verification_status || (activeSnapshot?.verification ? 'Verified' : 'Pending Review')}
              </div>
            </div>
          </div>
        </div>

        {/* Right Column: YOLO Flags Analysis & Human Verification Console */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: '0.65rem' }}>
          {/* Card 1: Flags Generated by YOLO */}
          <div className="table-card">
            <div style={{ padding: '0.45rem 0.65rem', background: 'var(--bg-table-header)', display: 'flex', justifyContent: 'space-between', alignItems: 'center', borderBottom: '1px solid var(--border-subtle)' }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '0.4rem' }}>
                <Cpu size={14} style={{ color: '#38bdf8' }} />
                <strong style={{ fontSize: '0.75rem' }}>
                  Flags Generated by YOLO Model
                </strong>
              </div>
              <span className={`badge ${isSnapFlagged ? 'badge-critical' : 'badge-compliant'}`}>
                {activeFlags.filter(f => f.severity !== 'Compliant Info').length} Anomalies Flagged
              </span>
            </div>

            <div style={{ padding: '0.6rem', display: 'flex', flexDirection: 'column', gap: '0.45rem', maxHeight: '200px', overflowY: 'auto' }}>
              {activeFlags.map((flag) => {
                const isCritical = flag.severity === 'Critical' || flag.severity === 'High';
                const isInfo = flag.severity === 'Compliant Info';

                return (
                  <div 
                    key={flag.id}
                    style={{
                      padding: '0.45rem 0.6rem',
                      background: isCritical ? 'rgba(239, 68, 68, 0.1)' : isInfo ? 'rgba(16, 185, 129, 0.08)' : 'var(--bg-secondary)',
                      border: `1px solid ${isCritical ? '#ef4444' : isInfo ? '#10b981' : 'var(--border-subtle)'}`,
                      borderRadius: '4px',
                      fontSize: '0.72rem'
                    }}
                  >
                    <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '0.2rem' }}>
                      <strong style={{ color: isCritical ? '#f87171' : isInfo ? '#34d399' : '#fbbf24', fontSize: '0.74rem' }}>
                        {isCritical ? '⚠️ ' : isInfo ? '✓ ' : 'ℹ️ '}{flag.title}
                      </strong>
                      <span className={`badge ${isCritical ? 'badge-critical' : isInfo ? 'badge-compliant' : 'badge-attention'}`} style={{ fontSize: '0.6rem', padding: '1px 5px' }}>
                        {flag.severity}
                      </span>
                    </div>

                    <div style={{ color: 'var(--text-muted)', fontSize: '0.68rem', lineHeight: '1.3' }}>
                      {flag.description}
                    </div>

                    <div style={{ marginTop: '0.25rem', fontSize: '0.64rem', color: 'var(--text-dim)' }}>
                      <strong>Protocol:</strong> {flag.action_required}
                    </div>
                  </div>
                );
              })}
            </div>
          </div>

          {/* Card 2: Human-in-the-Loop Verification Console */}
          <div className="table-card" style={{ flex: 1, display: 'flex', flexDirection: 'column' }}>
            <div style={{ padding: '0.45rem 0.65rem', background: 'var(--bg-table-header)', display: 'flex', justifyContent: 'space-between', alignItems: 'center', borderBottom: '1px solid var(--border-subtle)' }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '0.4rem' }}>
                <CheckCircle2 size={14} style={{ color: '#34d399' }} />
                <strong style={{ fontSize: '0.75rem' }}>
                  Officer Verification & Decision Console
                </strong>
              </div>
              <span className="badge badge-info" style={{ fontSize: '0.62rem' }}>
                {userRole || 'Officer'}
              </span>
            </div>

            <div style={{ padding: '0.65rem', display: 'flex', flexDirection: 'column', gap: '0.55rem', flex: 1 }}>
              {/* Existing Verification Status Stamp if already reviewed */}
              {activeSnapshot?.verification && (
                <div style={{
                  padding: '0.45rem 0.6rem',
                  background: 'rgba(56, 189, 248, 0.1)',
                  border: '1px solid #38bdf8',
                  borderRadius: '4px',
                  fontSize: '0.7rem'
                }}>
                  <strong style={{ color: '#38bdf8' }}>✓ Previously Verified:</strong>
                  <div style={{ marginTop: '0.15rem' }}>
                    Reviewed by <strong>{activeSnapshot.verification.officer_name}</strong> at{' '}
                    {new Date(activeSnapshot.verification.verified_at).toLocaleTimeString()}
                  </div>
                  <div style={{ color: 'var(--text-muted)', marginTop: '0.1rem' }}>
                    Decision: <strong>{activeSnapshot.verification.decision}</strong> • Note: {activeSnapshot.verification.remarks || 'No remarks'}
                  </div>
                </div>
              )}

              {/* Reviewing Officer Name */}
              <div>
                <label style={{ fontSize: '0.68rem', color: 'var(--text-dim)', display: 'block', marginBottom: '0.2rem' }}>
                  Reviewing Officer / Inspector:
                </label>
                <input 
                  type="text" 
                  value={officerName} 
                  onChange={(e) => setOfficerName(e.target.value)}
                  className="filter-select"
                  style={{ width: '100%', fontSize: '0.72rem', padding: '3px 8px' }}
                />
              </div>

              {/* Decision Radio / Action Buttons */}
              <div>
                <label style={{ fontSize: '0.68rem', color: 'var(--text-dim)', display: 'block', marginBottom: '0.25rem' }}>
                  Verification Verdict for YOLO Flags:
                </label>

                <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '0.35rem' }}>
                  <button 
                    type="button"
                    className={`btn-secondary ${decisionType === 'CONFIRM_FLAG' ? 'active' : ''}`}
                    onClick={() => setDecisionType('CONFIRM_FLAG')}
                    style={{
                      padding: '4px 6px',
                      fontSize: '0.68rem',
                      background: decisionType === 'CONFIRM_FLAG' ? 'rgba(239, 68, 68, 0.25)' : 'var(--bg-secondary)',
                      borderColor: decisionType === 'CONFIRM_FLAG' ? '#ef4444' : 'var(--border-subtle)',
                      color: decisionType === 'CONFIRM_FLAG' ? '#f87171' : 'var(--text-primary)'
                    }}
                  >
                    🔴 Confirm Flag
                  </button>

                  <button 
                    type="button"
                    className={`btn-secondary ${decisionType === 'DISMISS_FALSE_POSITIVE' ? 'active' : ''}`}
                    onClick={() => setDecisionType('DISMISS_FALSE_POSITIVE')}
                    style={{
                      padding: '4px 6px',
                      fontSize: '0.68rem',
                      background: decisionType === 'DISMISS_FALSE_POSITIVE' ? 'rgba(16, 185, 129, 0.25)' : 'var(--bg-secondary)',
                      borderColor: decisionType === 'DISMISS_FALSE_POSITIVE' ? '#10b981' : 'var(--border-subtle)',
                      color: decisionType === 'DISMISS_FALSE_POSITIVE' ? '#34d399' : 'var(--text-primary)'
                    }}
                  >
                    🟢 Dismiss Flag
                  </button>

                  <button 
                    type="button"
                    className={`btn-secondary ${decisionType === 'OVERRIDE_COUNT' ? 'active' : ''}`}
                    onClick={() => setDecisionType('OVERRIDE_COUNT')}
                    style={{
                      padding: '4px 6px',
                      fontSize: '0.68rem',
                      background: decisionType === 'OVERRIDE_COUNT' ? 'rgba(251, 191, 36, 0.25)' : 'var(--bg-secondary)',
                      borderColor: decisionType === 'OVERRIDE_COUNT' ? '#fbbf24' : 'var(--border-subtle)',
                      color: decisionType === 'OVERRIDE_COUNT' ? '#fbbf24' : 'var(--text-primary)'
                    }}
                  >
                    🟡 Manual Count
                  </button>
                </div>
              </div>

              {/* Manual Count Field if Overriding */}
              {decisionType === 'OVERRIDE_COUNT' && (
                <div>
                  <label style={{ fontSize: '0.68rem', color: 'var(--text-dim)', display: 'block', marginBottom: '0.2rem' }}>
                    Adjusted Headcount (Officer Count Override):
                  </label>
                  <input 
                    type="number" 
                    value={manualCount} 
                    onChange={(e) => setManualCount(e.target.value)}
                    className="filter-select"
                    style={{ width: '100%', fontSize: '0.72rem', padding: '3px 8px' }}
                    min="0"
                    max="100"
                  />
                </div>
              )}

              {/* Remarks Textarea */}
              <div style={{ flex: 1 }}>
                <label style={{ fontSize: '0.68rem', color: 'var(--text-dim)', display: 'block', marginBottom: '0.2rem' }}>
                  Verification Observations & Audit Justification:
                </label>
                <textarea 
                  rows={2}
                  value={remarks}
                  onChange={(e) => setRemarks(e.target.value)}
                  placeholder="e.g. Reviewed CCTV frame at timestamp 00:15. Trainees departed during practical workshop shift. Shortage confirmed."
                  className="filter-select"
                  style={{ width: '100%', fontSize: '0.7rem', padding: '4px 8px', resize: 'vertical' }}
                />
              </div>

              {/* Submit Action */}
              <button 
                className="btn-primary" 
                onClick={handleVerify}
                disabled={isSubmitting}
                style={{ width: '100%', justifyContent: 'center', padding: '6px' }}
              >
                <CheckCircle2 size={14} />
                <span>{isSubmitting ? 'Recording Verification...' : 'Submit Official Flag Verification'}</span>
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
